name: Lint & Test Contracts

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      # - name: Test
      #   run: npm run test
